# Generated by Django 2.2.5 on 2019-09-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_templates',
            name='template_file',
            field=models.CharField(default='survey_template', max_length=20),
        ),
    ]
