# Generated by Django 2.2.5 on 2019-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_templates_template_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_templates',
            old_name='template_file',
            new_name='input_template',
        ),
        migrations.AddField(
            model_name='survey_templates',
            name='output_template',
            field=models.CharField(default='survey_template', max_length=20),
        ),
    ]
