# Generated by Django 2.2.5 on 2019-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190916_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_templates',
            name='input_template',
            field=models.CharField(default='survey_template', max_length=50),
        ),
        migrations.AlterField(
            model_name='survey_templates',
            name='output_template',
            field=models.CharField(default='survey_template', max_length=50),
        ),
    ]
