# Generated by Django 2.2.5 on 2019-09-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190918_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_survey',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
